### ISSUE TITLE
It would be nice to have a FastMapInt; coming shortly

### ISSUE THREAD

**Issue by brewmanz** [RobTillaart/FastMap#5]
It would be nice to have a FastMapInt, using integer arithmetic, and also fixing the 'rounding switch' that happens as the input value to map drops below the in_min value, giving potentially unexpected results and a mapping step that is almost twice the expected width.
I will supply some code 'shortly'; it's only 5% faster than normal `map` but also includes bug (unexpected feature?) fix.

**Comment by RobTillaart** [comment]
@brewmanz 
Sorry for the late reply, apparently I missed some issues in the past.
I'm checking all my libs for open issues, so can take a few days.

Still a valid issue?

**Comment by RobTillaart** [comment]
Close this issue as it is old.
