### ISSUE TITLE
In fastMapDemo.ino, 'x = mapper.map(z);' has not-volatile z so compiler caches result, giving false speed

### ISSUE THREAD

**Issue by brewmanz** [RobTillaart/FastMap#6]
In fastMapDemo.ino, `x = mapper.map(z);` has `z` as not-volatile, so compiler caches result, giving false speed.
Once `z` is make volatile, 'performance factor' drops from 67 to 2.
Note that even this 2 is suspect, as the 'backwards' mapping of (0, 1023) to (20000, 3000) for normal `map` results in excess internal 8-bit operations. 
I am looking to refactor fastMapDemo.ino to calculate more accurate comparisons.

**Comment by RobTillaart** [comment]
z is also not volatile - > get your point.

'backwards' mapping is normal mapping from usage point of view, 
performance wise it might need separate investigation.

idea
Feed both with a random generator, both runs seeded same start value. 

A separate loop that measures the random generation overhead to subtract that part later.

**Comment by RobTillaart** [comment]
@brewmanz 
Sorry for the late reply, apparently I missed some issues in the past.
I'm checking all my libs for open issues, so can take a few days.

Is this still an actual issue?

**Comment by RobTillaart** [comment]
Close this issue as it is old.
